# Generated by Django 4.0 on 2024-03-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
    ]
